### ISSUE TITLE
Enhancement: Inverse Distance/Direction when projecting on the fly

### ISSUE THREAD

**Issue by ssibbett** [Esri/parcel-fabric-desktop-addins#15]
In my case, my fabric is projected in BC Albers, but I am editing in various UTM Zones (UTM Zone 10N, for example). When I use the Inverse Distance and Inverse Direction tools on the QA Add-In, the tools are inversing my data based on the coordinate system of the fabric (BC Albers), not the projection I have set in my data frame for my edit session (NAD 83 UTM Zone 10N).

**Comment by tekwen** [comment]
fixed:  https://github.com/Esri/parcel-fabric-desktop-addins/commit/37b85012fa9e687f5467c5d857a42d18d39591e7
