### ISSUE TITLE
ENH: Provide the ability to update z values on parcel points

### ISSUE THREAD

**Issue by ssibbett** [Esri/parcel-fabric-desktop-addins#16]
We've recently discovered there are a few workflows (Save XML/Append XML, Unjoin/Rejoin) that can result in elevation from control points being transferred to the Z attribute for parcel fabric points. This can cause very high computed minus observed values. The problem is that the Z field is not editable on the parcel points layer, and there is no way to remove the Z values that are transferred from control via the Field Calculator or Attributes window. It would be great if there was a tool on the Quality Control Add-In that could be used to remove Z values from parcel points.

**Comment by tekwen** [comment]
Enhancement available in version latest version, 4.4
